// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygusrelepdzolqtntkoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlndXNyZWxlcGR6b2xxdG50a29qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMjIwMjksImV4cCI6MjA2NjU5ODAyOX0.-IrhyxBDl6zjdI0nmxE7nDm8o8AUZy9UXuDEGlV4n_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});